/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicCronFetchMigrationsRouteImport } from './routes/api/public/cron/fetch-migrations'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronFetchMigrationsRoute =
  ApiPublicCronFetchMigrationsRouteImport.update({
    id: '/api/public/cron/fetch-migrations',
    path: '/api/public/cron/fetch-migrations',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/cron/fetch-migrations': typeof ApiPublicCronFetchMigrationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/cron/fetch-migrations': typeof ApiPublicCronFetchMigrationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/cron/fetch-migrations': typeof ApiPublicCronFetchMigrationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/cron/fetch-migrations'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/cron/fetch-migrations'
  id: '__root__' | '/' | '/api/public/cron/fetch-migrations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicCronFetchMigrationsRoute: typeof ApiPublicCronFetchMigrationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/fetch-migrations': {
      id: '/api/public/cron/fetch-migrations'
      path: '/api/public/cron/fetch-migrations'
      fullPath: '/api/public/cron/fetch-migrations'
      preLoaderRoute: typeof ApiPublicCronFetchMigrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicCronFetchMigrationsRoute: ApiPublicCronFetchMigrationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
